#
# Available repositories are listed here:
# https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
#

sudo: required
dist: trusty
group: deprecated-2017Q4

language: cpp

git:
  depth: 3

matrix:
  include:
    - env: COMPILER_VERSION=4.8
      os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - gnupg
            - libclang-dev
            - emacs
    - env: COMPILER_VERSION=6.0
      os: linux
      compiler: clang++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:
            - clang
            - gnupg
            - libclang-dev
            - emacs

install:
  - pip install --user --upgrade nose
  - pip install --user --upgrade PyHamcrest

script: ./scripts/travis.sh
